version: 2
updates:
  - package-ecosystem: "docker"
    directory: "docker"
    schedule:
      interval: "daily"
  - package-ecosystem: "terraform"
    directories:
      - "/"
      - "github-oidc-infra"
    schedule:
      interval: "daily"
    groups:
      terraform-dependencies:
        patterns:
          - "*"
