name: self-hosted-llm

services:
  ollama:
    container_name: ollama
    build:
      context: ./docker
      dockerfile: ollama.Dockerfile
    ports:
      - "11434:11434"
    volumes:
      - /mnt/data/ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  open-webui:
    container_name: open-webui
    build:
      context: ./docker
      dockerfile: webui.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - /mnt/data/open-webui:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_AUTH=false
      - DEFAULT_MODELS=llama3.3:latest
    depends_on:
      ollama:
        condition: service_started
