on:
  pull_request:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: AWS OIDC Auth
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          aws-region: us-east-2
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}

      - name: Create SSH keypair
        run: ssh-keygen -t rsa -b 2048 -q -N ""

      - name: Deploy LLM
        run: ./deploy.sh
